### ISSUE TITLE
Отсутствие rules.json в пакете на pypi.python.org

### ISSUE THREAD

**Issue by akadan47** [damirazo/Petrovich#1]
Добрый день, Дамир.
Спасибо за портирование петровича (думал сам начать, а оказалось уже сделано добрым человеком).
Но обнаружилось, что в пакете на pypi (https://pypi.python.org/pypi/Petrovich/0.1), нет файлика с правилами для петровича (rules.json). Из-за чего зависимость получается не совсем рабочая.

**Comment by damirazo** [comment]
Большое спасибо за сообщение. Действительно, оказалось, что забыл внести сборку этого файла в установщик пакета. Ошибку исправил и выложил на pypi обновленную версию пакета (0.1.1).
