### ISSUE TITLE
Совместимость с Python 3.x

### ISSUE THREAD

**Issue by iliadenisov** [damirazo/Petrovich#4]
Проблема заключается в кодировке файла **rules.json**, которую нужно указывать явным образом при открытии файла в Python 3.x.

main.py:36
```
with open(rules_path, 'r') as fp:
    self.data = json.load(fp)
```
Можно реализовать, например, так:
```
try:
    with open(rules_path, 'r', encoding='utf8') as fp:
        self.data = json.load(fp)
except:
    with open(rules_path, 'r') as fp:
        self.data = json.load(fp)
```
В результате получаем полностью совместимую с Python3.x библиотеку.

Спасибо!

**Comment by damirazo** [comment]
Исправлено в ПР https://github.com/damirazo/Petrovich/pull/5
